name: Build Clang Binary

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Clone LLVM
        uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project
          path: llvm
      - name: Install build dependencies
        run: sudo apt install -y build-essential cmake ninja-build bash
      - name: Build Clang
        run: cmake -S llvm/clang -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        working-directory: llvm
      - name: Install Clang
        run: ninja install
        working-directory: build
      - name: Upload Clang binary
        uses: actions/upload-artifact@v3
        with:
          name: clang-binary
          path: build/bin/clang



            
