name: Build Clang Binary

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Clone LLVM
        uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project
          path: llvm
      - name: Build Clang
        working-directory: llvm
        run: ls -la




            
