name: Build Clang Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: sudo apt install -y build-essential cmake ninja-build bash
      - name: Clone LLVM
        run: git clone --depth 1 https://github.com/llvm/llvm-project.git llvm
      - name: Build Clang
        working-directory: llvm
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - name: Install Clang
        working-directory: llmv/build
        run: ninja install
      - name: Upload Clang binary
        uses: actions/upload-artifact@v3
        with:
          name: clang-binary
          path: build/bin/clang





            
