name: Build Emacs Binary

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-focal

    steps:    
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1.4
            
