name: Build Clang Binary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Clone LLVM
        run: git clone --depth 1 https://github.com/llvm/llvm-project.git llvm
      - name: Build Clang
        working-directory: llvm
        run: ls -la





            
