name: Build Clang Binary

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: sudo apt install -y build-essential cmake ninja-build bash
      - name: Set up CMake environment
        run: source /usr/share/cmake-3.25/Modules/SetupCMake.sh
      - name: Build Clang
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -j4
        working-directory: clang
      - name: Install Clang
        run: ninja install
        working-directory: clang/build
      - name: Upload Clang binary
        uses: actions/upload-artifact@v3
        with:
          name: clang-binary
          path: clang/build/bin/clang


            
